import type { ReactNode } from 'react';
import manifest from '../../public/media/manifest.json';
import { business, home, values, programs, schedule, coaches, classes, classDetails, openTraining, timesFor } from '../data/content';
import { BookLink } from './Booking';

export function Photo({ name, alt, className = '', eager = false, sizes = '(max-width: 700px) 100vw, 50vw' }: { name: string; alt: string; className?: string; eager?: boolean; sizes?: string }) {
  const asset = manifest[name as keyof typeof manifest];
  if (!('derivatives' in asset)) return null;
  const standard = asset.derivatives[1];
  return <img className={`photo ${className}`} src={`/media/${standard.file}`} srcSet={asset.derivatives.map(d => `/media/${d.file} ${d.width}w`).join(', ')} sizes={sizes} alt={alt} width={standard.width} height={standard.height} loading={eager ? 'eager' : 'lazy'} decoding="async" />;
}
export function SectionTitle({ eyebrow, title, children, dark = false }: { eyebrow: string; title: ReactNode; children?: ReactNode; dark?: boolean }) {
  return <div className={`section-heading reveal ${dark ? 'on-dark' : ''}`}><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{children && <div className="section-intro">{children}</div>}</div>;
}
export function Values() {
  return <section className="values" aria-label="Our values"><div className="container values-grid">{values.map((v,i) => <article key={v.name}><span className="value-number">0{i+1}</span><div><h3>{v.name}</h3><p>{v.text}</p></div></article>)}</div></section>;
}
export function Community() {
  return <section className="section community"><div className="container split"><div className="community-picture reveal"><Photo name="community" alt="Students of all ages and levels training together on the mats at Praxis Jiu Jitsu" /><span className="image-caption">Adult & kids Jiu Jitsu</span></div><div className="split-copy reveal"><p className="eyebrow">Our academy</p><h2>Jiu Jitsu<br />in <em>Bernalillo.</em></h2><p>{home.community}</p><div className="facts"><div><strong>All levels</strong><span>Beginners welcome</span></div><div><strong>Ages 5+</strong><span>Kids & adults</span></div><div><strong>Free</strong><span>First class</span></div></div><a className="text-link" href="/about/">Get to know Praxis <span>↗</span></a></div></div></section>;
}
export function Mission() {
  return <section className="section mission" id="about"><div className="container"><div className="split mission-top"><div className="split-copy reveal"><p className="eyebrow">Our mission</p><h2>A focus on<br /><em>fundamentals.</em></h2>{home.mission.map(p => <p key={p}>{p}</p>)}<blockquote>{business.tagline}</blockquote><a className="text-link" href={business.tel}>Call or text: {business.phone} <span>↗</span></a></div><div className="mission-picture reveal"><Photo name="mission" alt="Coach Nikki Molina helping a young student at Praxis" /><div className="experience"><strong>10+</strong><span>Years of<br />experience</span></div></div></div><div className="mat-story reveal"><span className="eyebrow">The training space</span><div><h3>Floating-platform mat system.</h3><p>{home.mats}</p></div></div></div></section>;
}
export function Programs() {
  return <section className="section programs" id="programs"><div className="container"><SectionTitle eyebrow="What we offer" title={<>Programs for<br /><em>every level.</em></>}><p>{home.programIntro}</p><a href="/programs/" className="text-link">Explore all programs ↗</a></SectionTitle><div className="program-grid">{programs.map((p,i) => <article className="program-card reveal" key={p.name}><div className="program-image"><Photo name={p.image} alt={p.alt} sizes="(max-width: 700px) 100vw, 33vw" /><span className="program-index">0{i+1}</span></div><div className="program-copy"><h3>{p.name}</h3><p>{p.text}</p><BookLink className="text-link" /></div></article>)}</div></div></section>;
}
export function Schedule({ standalone = false }: { standalone?: boolean }) {
  return <section className="section schedule-section" id="schedule"><div className="container"><SectionTitle eyebrow="Weekly schedule" title={<>Class<br /><em>times.</em></>} dark><p>{standalone ? classes.scheduleIntro : home.scheduleIntro}</p><span className="eyebrow schedule-zone">Class times · Mountain time</span></SectionTitle><div className="schedule-grid" aria-label="Weekly class times">{schedule.map((d,i) => <article className="schedule-day" key={d.day}><div className="day-title"><h3>{d.day}</h3><span>0{i+1}</span></div><ul>{d.sessions.map(s => <li className={`session kind-${s.kind}`} key={s.name}><time>{s.time}</time><h4>{s.name}</h4>{s.detail && <p>{s.detail}</p>}</li>)}</ul></article>)}</div><div className="schedule-bottom"><div className="schedule-legend" aria-label="Class categories"><span>Kids</span><span>Adult Beginners</span><span>Adult Gi</span><span>Adult No-Gi</span><span>Open / Live Training</span></div><BookLink className="button button-cream" /></div></div></section>;
}
export function Coaches({ page = false }: { page?: boolean }) {
  return <section className={`section coaches ${page ? 'coaches-page' : ''}`} id="instructors"><div className="container"><SectionTitle eyebrow="The coaches" title={<>Meet your<br /><em>instructors.</em></>}>{!page && <a className="text-link" href="/instructors/">Meet your instructors ↗</a>}</SectionTitle><div className="coach-grid">{coaches.map(c => <article className="coach reveal" key={c.name}><div className="coach-photo"><Photo name={c.image} alt={c.name} /></div><div className="coach-copy"><p className="eyebrow">{c.role}</p><h3>{c.name}</h3><p>{c.bio}</p></div></article>)}</div></div></section>;
}
export function FreeClass({ classesPage = false }: { classesPage?: boolean }) {
  return <section className="free-class"><span className="background-word" aria-hidden="true">PRAXIS</span><div className="container free-class-inner"><div className="reveal"><p className="eyebrow">{classesPage ? 'No experience needed' : 'Ready to begin?'}</p><h2>Your first class<br />is <em>free.</em></h2><p>{classesPage ? classes.cta : home.cta}</p></div><div className="free-class-actions"><BookLink className="button button-cream" /><a href={business.tel} className="free-phone">{business.phone}</a><div className="contact-inline"><a href={business.tel}>Call to sign up ↗</a><a href={business.sms}>Text to sign up ↗</a></div></div></div></section>;
}
export function ContactSection({ page = false }: { page?: boolean }) {
  return <section className="section contact-section" id="contact"><div className="container contact-grid"><div className="reveal"><p className="eyebrow">Bernalillo, New Mexico</p><h2>Find us<br /><em>here.</em></h2><dl><div><dt>Location</dt><dd><a href={business.directions} target="_blank" rel="noreferrer">{business.street}<br />{business.city} ↗</a></dd></div><div><dt>Phone</dt><dd><a href={business.tel}>{business.phone}</a> <a className="small-link" href={business.sms}>Send a text ↗</a></dd></div><div><dt>Email</dt><dd><a href={`mailto:${business.email}`}>{business.email}</a></dd></div></dl><a className="text-link" href={business.instagram} target="_blank" rel="noreferrer">@praxisjjacademy <span>↗</span></a></div><div className="location-media">{page && <Photo name="exterior" alt="The exterior of Praxis Jiu Jitsu Academy in Bernalillo" />}<iframe title="Map showing Praxis Jiu Jitsu Academy in Bernalillo" src={business.map} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen /><a href={business.directions} className="map-caption" target="_blank" rel="noreferrer">965 US-550, Suite E <span>Get directions ↗</span></a></div></div></section>;
}
export function PageHero({ eyebrow, title, description, photo = 'team' }: { eyebrow: string; title: ReactNode; description: string; photo?: string }) {
  return <section className="page-hero"><Photo name={photo} alt="Training and community at Praxis Jiu Jitsu Academy" eager sizes="100vw" /><div className="page-hero-shade" /><div className="container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-hero-description">{description}</p></div></section>;
}
export function Newcomer() {
  return <section className="section newcomer"><div className="container split"><Photo name="kids" alt="Students drilling takedowns while a coach supervises at Praxis Jiu Jitsu" /><div className="split-copy"><p className="eyebrow">Every level</p><h2>New to<br /><em>Jiu Jitsu?</em></h2><p>{classes.start}</p><BookLink /></div></div></section>;
}
export function ProgramDetails() {
  return <section className="section program-details"><div className="container"><SectionTitle eyebrow="Our programs" title={<>Class <em>details.</em></>}><p>{classes.programsIntro}</p></SectionTitle><article className="kids-detail split"><div className="kids-detail-photo"><Photo name="mission" alt="Coach Nikki Molina working with a young student at Praxis Jiu Jitsu" /><div className="image-caption">Ages 5–12 · Coach Nikki Molina — Black Belt</div></div><div><p className="eyebrow">Ages 5–12</p><h3>Kids Jiu-Jitsu Program</h3>{classes.kids.map(p => <p key={p}>{p}</p>)}<div className="benefits"><div><h4>Physical benefits</h4><ul>{classes.physical.map(p => <li key={p}>{p}</li>)}</ul></div><div><h4>Life skills</h4><ul>{classes.life.map(p => <li key={p}>{p}</li>)}</ul></div></div><p className="detail-time">{timesFor('Kids Class')}</p><BookLink className="text-link" /></div></article><div className="class-detail-grid">{classDetails.map(c => <article key={c.name} className="class-detail reveal"><Photo name={c.image} alt={`${c.name} instruction at Praxis Jiu Jitsu`} sizes="(max-width: 700px) 100vw, 33vw" /><p className="eyebrow">{c.label}</p><h3>{c.name}</h3><p>{c.text}</p><div className="class-focus"><span>Focus</span><p>{c.focus}</p></div><p className="detail-time">{timesFor(c.name)}</p></article>)}</div><div className="open-training"><article><Photo name="community" alt="A full mat room of students training together on a Friday night at Praxis Jiu Jitsu" /><div><p className="eyebrow">All schools welcome</p><h3>Friday Live Training</h3><p>{openTraining.friday}</p><p className="detail-time">{timesFor('Live Training')}</p><p className="small-copy">Open to: All levels · All academies</p><a className="text-link" href={business.tel}>Questions? Call us ↗</a></div></article><article><Photo name="pinning" alt="Two adult students working a pinning position during class at Praxis Jiu Jitsu" /><div><p className="eyebrow">Saturdays · All levels</p><h3>All Levels No-Gi</h3>{openTraining.saturday.map(p => <p key={p}>{p}</p>)}<p className="detail-time">{timesFor('All Levels No-Gi')}</p><p className="small-copy">Open to: Beginners through advanced · No gi required</p></div></article></div></div></section>;
}
