import { createRoot, hydrateRoot } from 'react-dom/client';
import { App } from './App';
import '@fontsource/barlow/latin-400.css';
import '@fontsource/barlow/latin-500.css';
import '@fontsource/barlow/latin-600.css';
import '@fontsource/barlow-condensed/latin-600.css';
import '@fontsource/barlow-condensed/latin-600-italic.css';
import '@fontsource/barlow-condensed/latin-700.css';
import 'locomotive-scroll/locomotive-scroll.css';
import './styles.css';
const root = document.getElementById('root')!;
const app = <App path={location.pathname} />;
if (root.children.length) hydrateRoot(root, app);
else createRoot(root).render(app);
